pointcloud_to_laserscan_object_detection:
  ros__parameters:
    target_frame: base_link
    transform_tolerance: 0.1
    min_height: 0.1
    max_height: 0.3
    angle_min: -3.1415
    angle_max: 3.1415
    angle_increment: 0.0174533
    scan_time: 0.3333
    range_min: 0.4
    range_max: 100.0
    use_inf: True
    inf_epsilon: 1.0

pointcloud_to_laserscan_localization:
  ros__parameters:
    target_frame: livox_frame
    transform_tolerance: 0.1
    min_height: -0.2
    max_height: 0.2
    angle_min: -3.1415
    angle_max: 3.1415
      #angle_increment: 0.00436332
    angle_increment: 0.0174533
    scan_time: 0.3333
    range_min: 0.4
    range_max: 100.0
    use_inf: True
    inf_epsilon: 1.0
