waypoints:
  - id: 1
    position:
      x: 24.822750091552734
      y: -61.96527099609375
    euler_angle:
      z: 0.0
    functions:
      - function: restart
      - function: variable_waypoint_radius
        waypoint_radius: 3.0
  - id: 2
    position:
      x: -4.624066352844238
      y: -69.53016662597656
    euler_angle:
      z: 0.0
    functions:
      - function: variable_waypoint_radius
        waypoint_radius: 3.0
